#!/bin/bash
# ESP32 Motion Detector - Raspberry Pi Client Setup
# ==================================================

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Logging functions
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if running on Raspberry Pi
if [ ! -f /proc/device-tree/model ] || ! grep -q "Raspberry Pi" /proc/device-tree/model; then
    log_error "This script is designed for Raspberry Pi!"
    log_info "For server installation, use server/setup.sh"
    exit 1
fi

# Banner
echo "================================================"
echo " ESP32 Motion Detector - Raspberry Pi Client"
echo "================================================"
echo ""

PI_MODEL=$(cat /proc/device-tree/model)
log_info "Detected: $PI_MODEL"
echo ""

# Step 1: Check Python version
log_info "Checking Python version..."
if ! command -v python3 &> /dev/null; then
    log_error "Python 3 is not installed!"
    log_info "Installing Python 3..."
    sudo apt update && sudo apt install -y python3 python3-pip
fi

PYTHON_VERSION=$(python3 -c 'import sys; print(".".join(map(str, sys.version_info[:2])))')
REQUIRED_VERSION="3.8"

if [ "$(printf '%s\n' "$REQUIRED_VERSION" "$PYTHON_VERSION" | sort -V | head -n1)" != "$REQUIRED_VERSION" ]; then
    log_error "Python $REQUIRED_VERSION or higher is required (found: $PYTHON_VERSION)"
    exit 1
fi

log_success "Python $PYTHON_VERSION found"

# Step 2: Install system dependencies
log_info "Installing system dependencies..."

PACKAGES=(
    "python3-pip"
    "python3-venv"
    "python3-picamera2"  # For CSI camera
    "python3-lgpio"      # For GPIO (replaces RPi.GPIO on newer Pi OS)
)

sudo apt update
sudo apt install -y "${PACKAGES[@]}"

log_success "System dependencies installed"

# Step 3: Enable camera interface
log_info "Checking camera configuration..."

if ! grep -q "^camera_auto_detect=1" /boot/firmware/config.txt 2>/dev/null && \
   ! grep -q "^camera_auto_detect=1" /boot/config.txt 2>/dev/null; then
    log_warning "Camera auto-detect not enabled"
    read -p "Do you want to enable the camera? [Y/n]: " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Nn]$ ]]; then
        sudo raspi-config nonint do_camera 0
        log_success "Camera enabled"
        log_warning "A reboot is required after setup completes!"
        REBOOT_REQUIRED=true
    fi
else
    log_info "Camera is already enabled"
fi

# Test camera
log_info "Testing camera..."
if timeout 5 libcamera-hello --list-cameras &>/dev/null; then
    log_success "Camera detected and working"
elif timeout 5 rpicam-hello --list-cameras &>/dev/null; then
    log_success "Camera detected and working (rpicam)"
else
    log_warning "Camera test failed. This might be normal if camera is not connected yet."
    log_info "Connect your camera and run: libcamera-hello --list-cameras"
fi

# Step 4: Create virtual environment (optional)
read -p "Do you want to create a Python virtual environment? (recommended) [Y/n]: " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Nn]$ ]]; then
    if [ ! -d "venv" ]; then
        log_info "Creating virtual environment..."
        python3 -m venv venv --system-site-packages  # System packages for picamera2
        log_success "Virtual environment created"
    else
        log_info "Virtual environment already exists"
    fi

    log_info "Activating virtual environment..."
    source venv/bin/activate
    VENV_ACTIVE=true
    log_success "Virtual environment activated"
else
    VENV_ACTIVE=false
    log_warning "Skipping virtual environment. Installing globally."
fi

# Step 5: Upgrade pip
log_info "Upgrading pip..."
python3 -m pip install --upgrade pip

# Step 6: Install Python dependencies
log_info "Installing Python dependencies..."
pip3 install -r requirements.txt
log_success "Python dependencies installed"

# Step 7: Configure client
if [ ! -f config.yaml ]; then
    log_warning "config.yaml not found. Creating from template..."

    # Get server IP from user
    echo ""
    log_info "Enter server configuration:"
    read -p "Server IP address (e.g., 192.168.1.100): " SERVER_IP
    read -p "Server port [5000]: " SERVER_PORT
    SERVER_PORT=${SERVER_PORT:-5000}
    read -p "Auth token (from server config.yaml): " AUTH_TOKEN
    read -p "Device ID [RaspberryPi-CAM-01]: " DEVICE_ID
    DEVICE_ID=${DEVICE_ID:-RaspberryPi-CAM-01}

    # Create config.yaml
    cat > config.yaml << EOF
# Raspberry Pi Motion Detector Client - Configuration
# Auto-generated by setup script
# =====================================================

server:
  url: 'http://${SERVER_IP}:${SERVER_PORT}'
  auth_token: '${AUTH_TOKEN}'
  device_id: '${DEVICE_ID}'

pir:
  gpio_pin: 17  # BCM numbering (GPIO 17 = Pin 11)

motion:
  cooldown_seconds: 5

camera:
  resolution: [1280, 720]
  jpeg_quality: 85
  device_index: 0  # For USB camera (if not using CSI)

streaming:
  enabled: false
  fps: 5

logging:
  level: 'INFO'
  file: '/var/log/motion-detector-client.log'
EOF

    log_success "config.yaml created"
    echo ""
    log_info "Configuration saved:"
    log_info "  Server: http://${SERVER_IP}:${SERVER_PORT}"
    log_info "  Device ID: ${DEVICE_ID}"
else
    log_info "config.yaml already exists"
fi

# Create logs directory
log_info "Creating logs directory..."
mkdir -p logs
log_success "Logs directory created"

# Step 8: Setup GPIO permissions
log_info "Setting up GPIO permissions..."
if ! groups $USER | grep -q gpio; then
    sudo usermod -a -G gpio $USER
    log_warning "Added $USER to gpio group. Logout and login required!"
    LOGOUT_REQUIRED=true
fi

# Step 9: Test client (optional)
echo ""
read -p "Do you want to test the client? [Y/n]: " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Nn]$ ]]; then
    log_info "Testing client (press Ctrl+C to stop)..."
    log_warning "Make sure the server is running at the configured address!"
    echo ""

    # Check if PIR is connected
    if [ -f config.yaml ]; then
        PIR_PIN=$(grep "gpio_pin:" config.yaml | awk '{print $2}')
        log_info "PIR sensor should be connected to GPIO $PIR_PIN (BCM numbering)"
        log_info "  VCC -> 5V (Pin 2 or 4)"
        log_info "  GND -> GND (Pin 6, 9, 14, 20, 25, 30, 34, 39)"
        log_info "  OUT -> GPIO $PIR_PIN"
        echo ""
    fi

    sleep 2
    python3 pir_cam_client.py
else
    log_info "Skipping client test"
fi

# Step 10: Setup as systemd service (optional)
echo ""
read -p "Do you want to install as systemd service (auto-start on boot)? [Y/n]: " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Nn]$ ]]; then
    log_info "Creating systemd service..."

    SCRIPT_DIR=$(pwd)
    SERVICE_FILE="/etc/systemd/system/motion-detector-client.service"

    # For systemd service, use /var/log (journalctl captures stdout anyway)
    log_info "Note: Systemd service will log to journalctl"
    log_info "View logs with: sudo journalctl -u motion-detector-client -f"

    sudo tee $SERVICE_FILE > /dev/null << EOF
[Unit]
Description=ESP32 Motion Detector - Raspberry Pi Client
After=network.target

[Service]
Type=simple
User=$USER
WorkingDirectory=$SCRIPT_DIR
EOF

    if [ "$VENV_ACTIVE" = true ]; then
        echo "ExecStart=$SCRIPT_DIR/venv/bin/python3 $SCRIPT_DIR/pir_cam_client.py" | sudo tee -a $SERVICE_FILE > /dev/null
    else
        echo "ExecStart=/usr/bin/python3 $SCRIPT_DIR/pir_cam_client.py" | sudo tee -a $SERVICE_FILE > /dev/null
    fi

    sudo tee -a $SERVICE_FILE > /dev/null << EOF
Restart=always
RestartSec=10
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
EOF

    sudo systemctl daemon-reload
    sudo systemctl enable motion-detector-client.service

    log_success "Systemd service installed and enabled"
    log_info "Service commands:"
    log_info "  Start:   sudo systemctl start motion-detector-client"
    log_info "  Stop:    sudo systemctl stop motion-detector-client"
    log_info "  Status:  sudo systemctl status motion-detector-client"
    log_info "  Logs:    sudo journalctl -u motion-detector-client -f"
    echo ""

    read -p "Do you want to start the service now? [Y/n]: " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Nn]$ ]]; then
        sudo systemctl start motion-detector-client
        log_success "Service started"
        echo ""
        log_info "Checking service status..."
        sleep 2
        sudo systemctl status motion-detector-client --no-pager -l
    fi
fi

# Final instructions
echo ""
echo "================================================"
log_success "Setup completed successfully!"
echo "================================================"
echo ""

if [ "$LOGOUT_REQUIRED" = true ]; then
    log_warning "IMPORTANT: You must logout and login again for GPIO permissions to take effect!"
    echo ""
fi

if [ "$REBOOT_REQUIRED" = true ]; then
    log_warning "IMPORTANT: A reboot is required for camera changes to take effect!"
    echo ""
    read -p "Do you want to reboot now? [y/N]: " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        log_info "Rebooting..."
        sudo reboot
    else
        log_info "Please reboot manually later: sudo reboot"
    fi
fi

log_info "Next steps:"
echo ""
echo "1. Manual start (if not using systemd service):"
if [ "$VENV_ACTIVE" = true ]; then
    echo "   source venv/bin/activate"
fi
echo "   python3 pir_cam_client.py"
echo ""
echo "2. PIR Sensor Wiring (BCM numbering):"
if [ -f config.yaml ]; then
    PIR_PIN=$(grep "gpio_pin:" config.yaml | awk '{print $2}')
    echo "   VCC -> 5V (Pin 2 or 4)"
    echo "   GND -> GND (Pin 6, 9, 14, etc.)"
    echo "   OUT -> GPIO $PIR_PIN"
else
    echo "   See config.yaml for GPIO pin configuration"
fi
echo ""
echo "3. Test PIR sensor:"
echo "   Trigger motion and check server for uploaded images"
echo ""
log_info "For more information, see README.md and docs/RASPBERRY_PI.md"
