@echo off
REM ESP32 Motion Detector Server - Automated Setup for Windows
REM ============================================================

setlocal enabledelayedexpansion

echo ================================================
echo  ESP32 Motion Detector Server - Setup Script
echo ================================================
echo.

REM Check if Python is installed
echo [INFO] Checking Python installation...
python --version >nul 2>&1
if %errorlevel% neq 0 (
    echo [ERROR] Python is not installed or not in PATH!
    echo.
    echo Please install Python 3.8 or higher from:
    echo   https://www.python.org/downloads/
    echo.
    echo Make sure to check "Add Python to PATH" during installation!
    pause
    exit /b 1
)

REM Get Python version
for /f "tokens=2" %%i in ('python --version 2^>^&1') do set PYTHON_VERSION=%%i
echo [SUCCESS] Python %PYTHON_VERSION% found
echo.

REM Check if pip is available
echo [INFO] Checking pip installation...
python -m pip --version >nul 2>&1
if %errorlevel% neq 0 (
    echo [ERROR] pip is not installed!
    echo Installing pip...
    python -m ensurepip --default-pip
    if %errorlevel% neq 0 (
        echo [ERROR] Failed to install pip!
        pause
        exit /b 1
    )
)
echo [SUCCESS] pip is available
echo.

REM Ask about virtual environment
set /p VENV_CHOICE="Do you want to create a Python virtual environment? (recommended) [Y/n]: "
if /i "!VENV_CHOICE!"=="n" goto :skip_venv

REM Create virtual environment
if not exist "venv" (
    echo [INFO] Creating virtual environment...
    python -m venv venv
    if %errorlevel% neq 0 (
        echo [ERROR] Failed to create virtual environment!
        echo Continuing without virtual environment...
        goto :skip_venv
    )
    echo [SUCCESS] Virtual environment created
) else (
    echo [INFO] Virtual environment already exists
)

REM Activate virtual environment
echo [INFO] Activating virtual environment...
call venv\Scripts\activate.bat
if %errorlevel% neq 0 (
    echo [ERROR] Failed to activate virtual environment!
    echo Continuing without virtual environment...
    goto :skip_venv
)
echo [SUCCESS] Virtual environment activated
echo.
set VENV_ACTIVE=1
goto :continue_setup

:skip_venv
echo [WARNING] Skipping virtual environment. Installing globally.
echo.
set VENV_ACTIVE=0

:continue_setup
REM Upgrade pip
echo [INFO] Upgrading pip...
python -m pip install --upgrade pip
echo.

REM Install base requirements
echo [INFO] Installing Python dependencies...
echo [INFO] Installing base requirements...
python -m pip install -r requirements.txt
if %errorlevel% neq 0 (
    echo [ERROR] Failed to install base requirements!
    pause
    exit /b 1
)
echo.

REM Install Windows-specific requirements
echo [INFO] Installing Windows-specific requirements...
python -m pip install -r requirements-windows.txt
if %errorlevel% neq 0 (
    echo [WARNING] Failed to install Windows-specific requirements
    echo Some features may not work (e.g., Toast notifications)
)
echo.

echo [SUCCESS] Python dependencies installed
echo.

REM Download face recognition models
echo [INFO] Downloading face recognition models...

if not exist "models\face_detection_yunet_2023mar.onnx" (
    python models\download_models.py
    if %errorlevel% neq 0 (
        echo [ERROR] Failed to download face recognition models!
        echo Please download them manually from:
        echo   https://github.com/opencv/opencv_zoo/tree/master/models/face_detection_yunet
        echo   https://github.com/opencv/opencv_zoo/tree/master/models/face_recognition_sface
        pause
        exit /b 1
    )
    echo [SUCCESS] Face recognition models downloaded
) else (
    echo [INFO] Face recognition models already exist
)
echo.

REM Verify models exist
if not exist "models\face_detection_yunet_2023mar.onnx" (
    echo [ERROR] Face detection model not found!
    pause
    exit /b 1
)
if not exist "models\face_recognition_sface_2021dec.onnx" (
    echo [ERROR] Face recognition model not found!
    pause
    exit /b 1
)

REM Create config.yaml if it doesn't exist
if not exist "config.yaml" (
    echo [WARNING] config.yaml not found. Creating default config...

    REM Generate auth token
    for /f "delims=" %%i in ('python -c "import secrets; print(secrets.token_urlsafe(32))"') do set AUTH_TOKEN=%%i

    REM Create config.yaml
    (
        echo # ESP32 Motion Detector - Server Configuration
        echo # Auto-generated by setup script
        echo # ==============================================
        echo.
        echo server:
        echo   host: '0.0.0.0'
        echo   port: 5000
        echo   debug: false
        echo   log_level: 'INFO'
        echo   log_file: 'server.log'
        echo.
        echo security:
        echo   # Generated authentication token
        echo   auth_token: '!AUTH_TOKEN!'
        echo   require_auth_for_stream: true
        echo.
        echo storage:
        echo   image_dir: './captured_images'
        echo   max_images: 1000
        echo   max_age_days: 30
        echo.
        echo notifications:
        echo   enabled: true
        echo   backend: 'windows_toast'  # Windows Toast notifications
        echo   sound: true
        echo.
        echo face_recognition:
        echo   enabled: true  # Models downloaded
        echo   db_path: './faces.db'
        echo   faces_dir: './faces_db'
        echo.
        echo   threshold_strict: 0.35
        echo   threshold_loose: 0.50
        echo   margin_strict: 0.15
        echo   margin_loose: 0.08
        echo.
        echo   min_face_size: 10000
        echo   min_quality_score: 0.6
        echo.
        echo   auto_learning:
        echo     enabled: true
        echo     max_samples_per_person: 15
        echo     cooldown_seconds: 60
        echo     only_green_matches: true
        echo     replace_strategy: 'oldest'
        echo.
        echo   auto_create_person: true
        echo   new_person_name_template: 'Unbekannt #{count}'
        echo.
        echo stream:
        echo   target_fps: 10
        echo   jpeg_quality: 80
    ) > config.yaml

    echo [SUCCESS] config.yaml created with auth token: !AUTH_TOKEN!
    echo [WARNING] IMPORTANT: Save this auth token! You'll need it for ESP32 configuration.
    echo.
    echo !AUTH_TOKEN! > .auth_token
    echo [INFO] Auth token also saved to .auth_token file
    echo.
) else (
    echo [INFO] config.yaml already exists
    echo.
)

REM Create necessary directories
echo [INFO] Creating necessary directories...
if not exist "captured_images" mkdir captured_images
if not exist "faces_db" mkdir faces_db
echo [SUCCESS] Directories created
echo.

REM Get local IP address
for /f "tokens=2 delims=:" %%a in ('ipconfig ^| findstr /c:"IPv4"') do (
    set SERVER_IP=%%a
    goto :ip_found
)
:ip_found
set SERVER_IP=%SERVER_IP:~1%

REM Test server startup
set /p TEST_SERVER="Do you want to test the server startup? [Y/n]: "
if /i "!TEST_SERVER!"=="n" goto :skip_test

echo.
echo [INFO] Starting server (press Ctrl+C to stop^)...
echo [INFO] Server will be available at:
echo   Local:   http://localhost:5000
if defined SERVER_IP (
    echo   Network: http://!SERVER_IP!:5000
)
echo.
python app.py
goto :end_script

:skip_test
echo [INFO] Skipping server test
echo.

:end_script
REM Final instructions
echo.
echo ================================================
echo [SUCCESS] Setup completed successfully!
echo ================================================
echo.
echo Next steps:
echo.
echo 1. Start the server:
if !VENV_ACTIVE!==1 (
    echo    venv\Scripts\activate.bat  REM Activate virtual environment
)
echo    python app.py
echo.
echo 2. Configure your ESP32-CAM:
echo    - Edit esp32/include/secrets.h
echo    - Set AUTH_TOKEN from config.yaml
if defined SERVER_IP (
    echo    - Set SERVER_HOST to: !SERVER_IP!
)
echo.
echo 3. Open the web interface:
echo    http://localhost:5000
if defined SERVER_IP (
    echo    or http://!SERVER_IP!:5000
)
echo.
echo 4. Allow server through Windows Firewall if needed:
echo    - Windows Security ^> Firewall ^> Allow an app
echo    - Or run: netsh advfirewall firewall add rule name="ESP32 Server" dir=in action=allow protocol=TCP localport=5000
echo.
echo For more information, see README.md and docs/
echo.
pause
