#!/bin/bash
# ESP32 Motion Detector - Raspberry Pi Standalone Setup
# Installiert Server + Client auf einem Raspberry Pi
# ======================================================

set -e  # Exit on error

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
log_warning() { echo -e "${YELLOW}[WARNING]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Check Raspberry Pi
if [ ! -f /proc/device-tree/model ] || ! grep -q "Raspberry Pi" /proc/device-tree/model; then
    log_error "This script is designed for Raspberry Pi!"
    exit 1
fi

PI_MODEL=$(cat /proc/device-tree/model)
log_info "Detected: $PI_MODEL"

# Recommend Pi 4/5
if ! echo "$PI_MODEL" | grep -qE "Raspberry Pi (4|5)"; then
    log_warning "Raspberry Pi 4 or 5 recommended for Standalone mode!"
    log_warning "Pi 3 will work but Face Recognition will be slow (~2s per image)"
    read -p "Continue anyway? [y/N]: " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
fi

echo "================================================"
echo " Raspberry Pi Standalone Setup"
echo " Server + Client on ONE device"
echo "================================================"
echo ""

# Determine base directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
SERVER_DIR="$REPO_ROOT/Server"
CLIENT_DIR="$REPO_ROOT/Raspberry-Pi/Client"

log_info "Repository root: $REPO_ROOT"
log_info "Server directory: $SERVER_DIR"
log_info "Client directory: $CLIENT_DIR"
echo ""

# Step 1: Check Python
log_info "Checking Python version..."
if ! command -v python3 &> /dev/null; then
    log_error "Python 3 not found!"
    log_info "Installing Python 3..."
    sudo apt update && sudo apt install -y python3 python3-pip python3-venv
fi

PYTHON_VERSION=$(python3 -c 'import sys; print(".".join(map(str, sys.version_info[:2])))')
if [ "$(printf '%s\n' "3.8" "$PYTHON_VERSION" | sort -V | head -n1)" != "3.8" ]; then
    log_error "Python 3.8+ required (found: $PYTHON_VERSION)"
    exit 1
fi
log_success "Python $PYTHON_VERSION found"
echo ""

# Step 2: Install system dependencies
log_info "Installing system dependencies..."
sudo apt update
sudo apt install -y \
    python3-pip \
    python3-venv \
    python3-picamera2 \
    python3-lgpio \
    libnotify-bin

log_success "System dependencies installed"
echo ""

# Step 3: Enable camera
log_info "Checking camera configuration..."
if ! grep -q "^camera_auto_detect=1" /boot/firmware/config.txt 2>/dev/null && \
   ! grep -q "^camera_auto_detect=1" /boot/config.txt 2>/dev/null; then
    log_warning "Camera not enabled"
    read -p "Enable camera? [Y/n]: " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Nn]$ ]]; then
        sudo raspi-config nonint do_camera 0
        log_success "Camera enabled"
        REBOOT_REQUIRED=true
    fi
fi
echo ""

# Step 4: Install SERVER
log_info "=== INSTALLING SERVER ==="
cd "$SERVER_DIR"

# Create venv
if [ ! -d "venv" ]; then
    log_info "Creating virtual environment for server..."
    python3 -m venv venv
fi

# Activate and install
log_info "Installing server dependencies..."
source venv/bin/activate
pip install --upgrade pip
pip install -r requirements.txt
pip install -r requirements-linux.txt 2>/dev/null || log_warning "No Linux-specific requirements"

# Download models
log_info "Downloading face recognition models..."
if [ ! -f "models/face_detection_yunet_2023mar.onnx" ]; then
    python models/download_models.py
else
    log_info "Models already exist"
fi

# Generate auth token
AUTH_TOKEN=$(python -c "import secrets; print(secrets.token_urlsafe(32))")

# Create server config
if [ ! -f "config.yaml" ]; then
    log_info "Creating server config.yaml..."
    cat > config.yaml << EOF
# Raspberry Pi Standalone - Server Configuration
# Auto-generated by setup script

server:
  host: '0.0.0.0'
  port: 5000
  debug: false
  log_level: 'INFO'
  log_file: 'server.log'

security:
  auth_token: '$AUTH_TOKEN'
  require_auth_for_stream: true

storage:
  image_dir: './captured_images'
  max_images: 1000
  max_age_days: 30

notifications:
  enabled: false  # Headless Pi
  backend: 'disabled'
  sound: false

face_recognition:
  enabled: true
  db_path: './faces.db'
  faces_dir: './faces_db'

  threshold_strict: 0.35
  threshold_loose: 0.50
  margin_strict: 0.15
  margin_loose: 0.08

  min_face_size: 10000
  min_quality_score: 0.6

  auto_learning:
    enabled: true
    max_samples_per_person: 12  # Reduced for Pi performance
    cooldown_seconds: 60
    only_green_matches: true
    replace_strategy: 'oldest'

  auto_create_person: true
  new_person_name_template: 'Unbekannt #{count}'

stream:
  target_fps: 8  # Reduced for Pi
  jpeg_quality: 80
EOF
    log_success "Server config created with auth token: $AUTH_TOKEN"
else
    log_info "Server config.yaml already exists"
fi

# Create directories
mkdir -p captured_images faces_db
deactivate

log_success "Server installation complete"
echo ""

# Step 5: Install CLIENT
log_info "=== INSTALLING CLIENT ==="
cd "$CLIENT_DIR"

# Install client dependencies
log_info "Installing client dependencies..."
pip3 install -r requirements.txt

# Create client config
if [ ! -f "config.yaml" ]; then
    log_info "Creating client config.yaml..."
    cat > config.yaml << EOF
# Raspberry Pi Standalone - Client Configuration
# Auto-generated by setup script

server:
  url: 'http://localhost:5000'  # Local server
  auth_token: '$AUTH_TOKEN'  # Matches server token
  device_id: 'RaspberryPi-Standalone'

pir:
  gpio_pin: 17  # BCM numbering

motion:
  cooldown_seconds: 5

camera:
  resolution: [1280, 720]  # Adjust based on Pi model
  jpeg_quality: 85
  device_index: 0

streaming:
  enabled: false  # Not needed for standalone
  fps: 5

logging:
  level: 'INFO'
  file: './logs/client.log'
EOF
    log_success "Client config created"
else
    log_info "Client config.yaml already exists"
fi

# Create logs directory
mkdir -p logs

log_success "Client installation complete"
echo ""

# Step 6: Setup systemd services
log_info "=== SETTING UP SYSTEMD SERVICES ==="

# Server service
log_info "Creating server systemd service..."
sudo tee /etc/systemd/system/motion-detector-server.service > /dev/null << EOF
[Unit]
Description=Motion Detector Server (Standalone)
After=network.target

[Service]
Type=simple
User=$USER
Group=$USER
WorkingDirectory=$SERVER_DIR
Environment="PYTHONUNBUFFERED=1"
ExecStart=$SERVER_DIR/venv/bin/python app.py

Restart=on-failure
RestartSec=10s

StandardOutput=journal
StandardError=journal
SyslogIdentifier=motion-server

[Install]
WantedBy=multi-user.target
EOF

# Client service
log_info "Creating client systemd service..."
sudo tee /etc/systemd/system/motion-detector-client.service > /dev/null << EOF
[Unit]
Description=Motion Detector Client (Standalone)
After=network.target motion-detector-server.service

[Service]
Type=simple
User=$USER
Group=$USER
WorkingDirectory=$CLIENT_DIR
Environment="PYTHONUNBUFFERED=1"
ExecStart=/usr/bin/python3 pir_cam_client.py

Restart=on-failure
RestartSec=10s

StandardOutput=journal
StandardError=journal
SyslogIdentifier=motion-client

SupplementaryGroups=gpio video

[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload

log_success "Systemd services created"
echo ""

# Step 7: Enable and start services
read -p "Enable and start services now? [Y/n]: " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Nn]$ ]]; then
    log_info "Enabling services..."
    sudo systemctl enable motion-detector-server
    sudo systemctl enable motion-detector-client

    log_info "Starting server..."
    sudo systemctl start motion-detector-server
    sleep 5  # Wait for server to start

    log_info "Starting client..."
    sudo systemctl start motion-detector-client
    sleep 2

    log_info "Checking service status..."
    echo ""
    echo "=== Server Status ==="
    sudo systemctl status motion-detector-server --no-pager -l || true
    echo ""
    echo "=== Client Status ==="
    sudo systemctl status motion-detector-client --no-pager -l || true
    echo ""
fi

# Step 8: Final instructions
echo "================================================"
log_success "Standalone Setup Complete!"
echo "================================================"
echo ""
echo "Configuration:"
echo "  Auth Token: $AUTH_TOKEN"
echo "  Server URL: http://localhost:5000 (from Pi)"
echo ""
echo "Access Web Interface:"
PI_IP=$(hostname -I | awk '{print $1}')
if [ ! -z "$PI_IP" ]; then
    echo "  From this Pi: http://localhost:5000"
    echo "  From network: http://$PI_IP:5000"
    echo "  Alternative:  http://$(hostname).local:5000"
fi
echo ""
echo "Service Commands:"
echo "  View status:  sudo systemctl status motion-detector-server"
echo "  View status:  sudo systemctl status motion-detector-client"
echo "  View logs:    sudo journalctl -u motion-detector-server -f"
echo "  View logs:    sudo journalctl -u motion-detector-client -f"
echo "  Restart:      sudo systemctl restart motion-detector-server"
echo "  Restart:      sudo systemctl restart motion-detector-client"
echo "  Stop:         sudo systemctl stop motion-detector-server motion-detector-client"
echo ""
echo "PIR Sensor Wiring:"
echo "  VCC → Pi Pin 2 (5V)"
echo "  GND → Pi Pin 6 (GND)"
echo "  OUT → Pi Pin 11 (GPIO 17)"
echo ""

if [ "$REBOOT_REQUIRED" = true ]; then
    log_warning "A reboot is required for camera changes!"
    read -p "Reboot now? [y/N]: " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        log_info "Rebooting..."
        sudo reboot
    else
        log_info "Please reboot manually: sudo reboot"
    fi
fi

log_info "Setup complete! Trigger the PIR sensor to test."
